### ISSUE TITLE
Parent directory unwrapping

### ISSUE THREAD

**Issue by arslancharyev31** [Jindetta/PD2-Custom-Profile-Set#2]
Good day.
The current directory hierarchy is a bit confusing for me, since I cannot directly `git clone` it to my `mods` folder. I have to first extract `Custom Profile Set` from the `PD2-Custom-Profile-Set` folder to `mods` folder if I wish to test it in game. Then, after making changes and testing them, I have to copy it back to `PD2-Custom-Profile-Set` folder if I wish to commit it without messing up with folder structure. Hence, I was wondering what is the reason for having `PD2-Custom-Profile-Set` wrapping `Custom Profile Set` folder?

**Comment by Jindetta** [comment]
Clone it somewhere and make symbolic link to "Custom Profile Set" directory
which contains lua files.

mklink /D "Custom Profile Set" *path to cloned repo directory*

Run this command from your Payday 2/mods directory

to 23. toukokuuta 2019 klo 18.33 Arslan Charyyev <notifications@github.com>
kirjoitti:

**Comment by arslancharyev31** [comment]
Symlinks... I see now, thanks :)
But still, out of curiosity may I ask if there is a specific reason for such arrangement? Or is it just arbitrary?

**Comment by Jindetta** [comment]
Hey.

The reasoning behind this is that I have multiple repositories related to
Payday 2 mods and I don't want to mix those with the other mods that I use.
It makes mod management a bit easier. That's pretty much it.

Symbolic links are easy solution to maintain this and that's why I ended up
using them.

to 23. toukok. 2019 klo 19.46 Arslan Charyyev (notifications@github.com)
kirjoitti:
